---
title: "Metabolomics"
---

See [Figure 2](index.qmd#fig-2) for the meanings of the abbreviations used in this chapter.

## 1. GC-MS (nominal mass)

The environment for GC-MS data analysis in MS-DIAL5 is now under construction. Please use version 4 series for which the tutorial is available here: <https://mtbinfo-team.github.io/mtbinfo.github.io/MS-DIAL/tutorial.html#chapter-4>

## 2. GC-MS (high resolution)

## 3. LC/MS or LC/MS/MS (data dependent MS/MS) project with user-defined MS/MS database (MSP format)

Here, a project involving data-dependent MS/MS acquisition in conjunction with a user-defined MSP library (a composite library comprising MassBank, GNPS, and Respect) is presented.

### Input Data

This section utilizes a total of 6 ABF files, with the MSP file being located in the same ZIP folder as this demonstration. The ABF files for this demonstration can be downloaded from <http://prime.psc.riken.jp/compms/msdial/download/demo/20160805-Wine-DDA-Pos-Demo%20files.zip>. The experimental protocol has been previously described in the following research: <http://pubs.acs.org/doi/abs/10.1021/acs.jafc.5b04890>.

#### Experiment summary:

-   **Liquid chromatography:** total 4 min run per sample with Kinetex C18 2.6 μm (50×1.0 mm)
-   **Solvent A:** water with 0.1% acetic acid
-   **Solvent B:** acetonitrile with 0.1% acetic acid
-   **Mass spectrometer:** data dependent method with positive ion mode
    -   Collision energy: 35 V
    -   Collision energy spread: 15 V
    -   Cycle time: 125 ms
    -   Mass range: m/z 60-1250

### The video tutorial for the MS-DIAL operation

{{< video https://www.youtube.com/embed/cZY7wqF5Wdo >}}

### Key points in the MS-DIAL operation

1.  All sample `Type`s are `Sample`. The input data here does not contain `QC` or `Blank`.
2.  For this input data, set a different `Class ID` for each sample.
3.  You can paste Excel cells to MS-DIAL sample table.

## 3. CE-MS/MS

## 4. All ion fragmentation with multiple collision energies

## 5. MS-DIAL isotope tracking function
