---
title: "Lipidomics"
editor: 
  markdown: 
    wrap: 72
---

## 1. DI-MS/MS

A project dealing with data dependent DI-MS acquisition in combination
with the in silico retention time and MS/MS databases for lipids is
demonstrated.

This tutorial uses 15 demonstration files which are downloadable from
the below link.\
(*add the corresponding link*)

**Experiment summary:**\
(*add experiment summary*)

### 1-1 Starting up your project

![Figure 1 Starting up a project in MS-DIAL. First open the MSDIAL.exe
file in the downloaded folder (1). Click on new project (2). You can
name your project according to your preferences (3). Browse to the
location of your experimental files (here your processing files will be
also stored) (3). Click next and then continue to the second left side
bar "Raw measurement files". Here click browse to access your raw data
files
(4).](images/Chapter2/Fig1%20Starting%20up%20a%20project%20in%20MS-DIAL.png){#fig-1}

![Figure 2 Importing raw data files and setting up the measurement
parameters. Change the type of file according to your vendor format and
select raw data files which you want to import (note: the data files
will be imported according to the alphabetical order) (1). After
inserting your raw data files, you will be able to further assign
identifiers to your measurements by sample type (Sample, Standard, QC,
Blank), class ID (according to your experimental setup), and you can
also set the batch (if you analyzed multiple batches), analytical order,
dilution factor, or possibly exclude some samples from further data
processing (2). It is advisable to select the blanks and QC samples (if
measured) to be able to use all functions of MS-DIAL (such as blank
filtering or LOWESS signal correction based on QCs) (3). After clicking
next and selecting the "Measurement parameters" in the left side tab you
can specify your analytical setup according to this figure (more details
are provided in the [intruduction
section](https://mtbinfo-team.github.io/msdial5tutorial/#fig-5))
(4).](images/Chapter2/Fig2%20Importing%20raw%20data%20files%20and%20setting%20up%20the%20measurement%20parameters.png){#fig-2}

## 2. LC-MS/MS (data independent MS/MS) project for lipidomics using in silico retention time and theoretical MS/MS library of lipids

## 3. LC-MS/MS (EAD) - deep structural lipid annotation

## 4. SFC-MS/MS

## 5. DI-IM-MS/MS

## 6. LC-IM-MS/MS
