---
title: "Console app"
format:
  html:
    toc: false
editor: 
  markdown: 
    wrap: 72
---

While the standard MS-DIAL version provides a graphical user interface (GUI) primarily for Windows,
the Console app allows users to perform high-throughput data processing across multiple operating systems, including Windows, Linux, and macOS.

## Key Features and Capabilities

- **Automation and Scripting:** Designed for users who need to automate large-scale data processing or integrate MS-DIAL into bioinformatics pipelines.
- **Core Processing Steps:** It performs essential data analysis tasks without the GUI, including:
  - **Peak Detection:** Identifying signals from complex mass spectrometry raw data.
  - **Deconvolution:** Separating overlapping peaks to identify individual compounds.
  - **Alignment:** Matching peaks across different samples for comparative analysis.
  - **Identification:** Annotating metabolites using spectral libraries (e.g., MSP format files).

- **Supported Data Formats:** The app can process various raw data formats such as **mzML, wiff, raw, and D,** and it supports multiple instruments (GC/MS, LC/MS/MS) and vendors.
- **Outputs:** It generates 3 metabolome table formats (**.mdalign, .mdmsp, .mzTab**) and 2 types (**.mdmsp, .mdpeak**) peak annotation data formats used for downstream/statistical analysis.

## Console app in action

Download our demo mzML files and a Console app configuration file (we call it method file) from [https://zenodo.org/records/18336159](https://zenodo.org/records/18336159).

(Below is an example of using the Console app for Linux.)

1. Download the latest Console app for Linux ([https://github.com/systemsomicslab/MsdialWorkbench/releases/tag/MSDIAL-v5.5.260319](https://github.com/systemsomicslab/MsdialWorkbench/releases/tag/MSDIAL-v5.5.260319)) with running

    ```bash
    curl -L -O https://github.com/systemsomicslab/MsdialWorkbench/releases/download/MSDIAL-v5.5.260319/MSDIAL.console.v5.5.260319-linux-net8.zip
    ```

2. Create a directory for the Console app and unzip the downloaded file with running

    ```bash
    mkdir msdial5console && mv MSDIAL.console.v5.5.260319-linux-net8.zip msdial5console/ && cd msdial5console/ && unzip MSDIAL.console.v5.5.260319-linux-net8.zip
    ```

3. Download the demo mzML raw datafiles zip ([https://doi.org/10.5281/zenodo.18336159](https://doi.org/10.5281/zenodo.18336159)) and unzip it with running
  
    ```bash
    curl -L -C - -o zenodo18336159.zip "https://zenodo.org/records/18336159/files/zenodo18336159.zip?download=1" && unzip zenodo18336159.zip
    ```

6. Run the `MSDIALCUI` command:

    ```bash
    chmod +x ./MSDIALCUI && \
    ./MSDIALCUI lcms -i zenodo18336159/consoleapp_demo_csvimportfiles.csv -o zenodo18336159/output/ -m zenodo18336159/zenodo18336159_method.txt -p
    ```

The `-i` option takes the path to the raw data and the path to the CSV file containing its metadata as arguments.
The contents of the input CSV file will be as follows.

|file_path                                |file_name            |file_type|class_id|acquisition_type|batch_order|analytical_order|factor|Included|
|-----------------------------------------|---------------------|---------|--------|----------------|-----------|----------------|------|--------|
|zenodo18336159/20230406_blank_NEG_1.mzML |20230406_blank_NEG_1 |Blank    |Blank   |DDA             |1          |1               |1     |TRUE    |
|zenodo18336159/20230406_feces_1_NEG.mzML |20230406_feces_1_NEG |Sample   |feces   |DDA             |1          |2               |1     |TRUE    |
|zenodo18336159/20230406_feces_2_NEG.mzML |20230406_feces_2_NEG |Sample   |feces   |DDA             |1          |3               |1     |TRUE    |
|zenodo18336159/20230406_feces_3_NEG.mzML |20230406_feces_3_NEG |Sample   |feces   |DDA             |1          |4               |1     |TRUE    |
|zenodo18336159/20230407_plasma_1_NEG.mzML|20230407_plasma_1_NEG|Sample   |plasma  |DDA             |1          |5               |1     |TRUE    |
|zenodo18336159/20230407_plasma_2_NEG.mzML|20230407_plasma_2_NEG|Sample   |plasma  |DDA             |1          |6               |1     |TRUE    |
|zenodo18336159/20230407_plasma_3_NEG.mzML|20230407_plasma_3_NEG|Sample   |plasma  |DDA             |1          |7               |1     |TRUE    |

The first **8** columns of the header row must be
`file_path, file_name, file_type, class_id, acquisition_type, batch_order, analytical_order, factor`

Information in 9th column and beyond will be ignored.

The `file_path` column can contain either an absolute or relative path to the raw data.
Relative paths will be relative to the `MSDIALCUI` file.

The `-o` option specifies the output destination.
The Console app at the path specified by the -o option outputs alignment results in **3** formats (mzTab, mdalign, mdmsp) and peak annotation results for each raw data set in **2** formats (mdpeak, mdmsp).

If you give the zenodo18336159 dataset to the Console app, the output file will look like this:

```
20230406_blank_NEG_1.mdmsp   20230406_feces_2_NEG.mdmsp   20230407_plasma_1_NEG.mdmsp   20230407_plasma_3_NEG.mdmsp      AlignResult-20261221921.mzTab
20230406_blank_NEG_1.mdpeak  20230406_feces_2_NEG.mdpeak  20230407_plasma_1_NEG.mdpeak  20230407_plasma_3_NEG.mdpeak     Project-2601220721.mdproject
20230406_feces_1_NEG.mdmsp   20230406_feces_3_NEG.mdmsp   20230407_plasma_2_NEG.mdmsp   AlignResult-20261221921.mdalign
20230406_feces_1_NEG.mdpeak  20230406_feces_3_NEG.mdpeak  20230407_plasma_2_NEG.mdpeak  AlignResult-20261221921.mdmsp
```

The -m option specifies the path to a configuration file called the method file.

The important parts of the method file are the first few lines below.

```
MS1 data type: Centroid
MS2 data type: Centroid
Ion mode: Negative
Target omics: Lipidomics
Ionization: ESI
Machine category: LCMS
Instrument type:
Instrument:
Authors:
License:
Comment:
Msp file path: ./zenodo18336159/MSMS-Public_all-neg-VS19.msp
Lbm file path: ./zenodo18336159/Msp20241113163720_NCDK-TUAT-FastLC_converted_dev.lbm2
Text DB file path: ./zenodo18336159/20200121_MsdialTxtDB_Neg_EquiSPLASH_rapid.txt
Isotope text DB file path:
Compounds library file path for target detection:
Compounds library file path for RT correction:
```

Below we will explain some of the most important lines.

```
Ion mode: Negative
```

Please set the ion mode to either Positive or Negative.
If the mode is different from the actual mode of the raw data, the process will not complete.

```
Msp file path: ./zenodo18336159/MSMS-Public_all-neg-VS19.msp
Lbm file path: ./zenodo18336159/Msp20241113163720_NCDK-TUAT-FastLC_converted_dev.lbm2
Text DB file path: ./zenodo18336159/20200121_MsdialTxtDB_Neg_EquiSPLASH_rapid.txt
```

Please set the path to the library used for metabolite or lipid annotation.
Absolute and relative paths can be used for the library path.
Relative paths are relative to the MSDIALCUI file.
In addition to the well-known msp file format, MS-DIAL's dedicated lbm file or a text file in a proprietary text format can be used.
See [https://systemsomicslab.github.io/compms/msdial/main.html#MSP](https://systemsomicslab.github.io/compms/msdial/main.html#MSP) for details on those file formats.

This concludes the explanation of the Console app.
If there is anything missing from the explanation, please add an issue to [https://github.com/systemsomicslab/msdial5tutorial/issues](https://github.com/systemsomicslab/msdial5tutorial/issues).
