---
title: "Lipidomics"
editor: 
  markdown: 
    wrap: 72
---

See [Figure 2](index.qmd#fig-2) for the meanings of the abbreviations used in this chapter.

## 1. DI-MS/MS (DDA)

A project dealing with data dependent DI-MS acquisition in combination
with the in silico retention time and MS/MS databases for lipids is
demonstrated.

This tutorial uses 15 demonstration files which are downloadable from
the below link.\

[http://prime.psc.riken.jp/compms/msdial/download/demo/dims.zip](http://prime.psc.riken.jp/compms/msdial/download/demo/dims.zip)

**Experiment summary:**\

The direct infusion MS data analyzing plasma, white adipose tissue (WAT), muscle, and liver of mice in addition to the procedure blank samples.
The MS/MS spectrum was acquired by information dependent acquisition (IDA) mode of SCIEX meaning data dependent acquisition (DDA).


### 1-1 Starting up your project

![Figure 1 Starting up a project in MS-DIAL. First open the MSDIAL.exe
file in the downloaded folder (1). Click on new project (2). You can
name your project according to your preferences (3). Browse to the
location of your experimental files (here your processing files will be
also stored) (3). Click next and then continue to the second left side
bar "Raw measurement files". Here click browse to access your raw data
files
(4).](images/Chapter2/Fig1%20Starting%20up%20a%20project%20in%20MS-DIAL.png){#fig-1}

![Figure 2 Importing raw data files and setting up the measurement
parameters. Change the type of file according to your vendor format and
select raw data files which you want to import (note: the data files
will be imported according to the alphabetical order) (1). After
inserting your raw data files, you will be able to further assign
identifiers to your measurements by sample type (Sample, Standard, QC,
Blank), class ID (according to your experimental setup), and you can
also set the batch (if you analyzed multiple batches), analytical order,
dilution factor, or possibly exclude some samples from further data
processing (2). It is advisable to select the blanks and QC samples (if
measured) to be able to use all functions of MS-DIAL (such as blank
filtering or LOWESS signal correction based on QCs) (3). After clicking
next and selecting the "Measurement parameters" in the left side tab you
can specify your analytical setup according to this figure (more details
are provided in the [intruduction
section](https://mtbinfo-team.github.io/msdial5tutorial/#fig-5))
(4).](images/Chapter2/Fig2%20Importing%20raw%20data%20files%20and%20setting%20up%20the%20measurement%20parameters.png){#fig-2}

To see the above operation in YouTube, check out the following

{{< video https://www.youtube.com/watch?v=Zo7qBcduc1E >}}


## 2. DI-MS/MS (MSall)

A project dealing with MSall DI-MS acquisition in combination with the
in silico retention time and MS/MS databases for lipids is demonstrated.

Additionally, you can watch our tutorial video:
{{< video https://www.youtube.com/watch?v=YiAj0K37-CE&ab_channel=MS-DIALproject >}}

## 3. DI-MS/MS (DDA)

A project dealing with DDA DI-MS acquisition in combination with the
in silico retention time and MS/MS databases for lipids is demonstrated.

Additionally, you can watch our tutorial video:
{{< video https://www.youtube.com/watch?v=Zo7qBcduc1E&ab_channel=MS-DIALproject >}}

## 4. LC-MS/MS (SWATH)

A project dealing with data independent LC-MS acquisition using the
Sequential Window Acquisition of all Theoretical Mass Spectra (SWATH-MS)
in combination with the in silico retention time and MS/MS databases for
lipids is demonstrated.

### Input Data

This tutorial uses 23 demonstration files which are downloadable from <http://prime.psc.riken.jp/archives/data/DropMet/019/20140809_MSDIAL_DemoFiles_Swath(abf).zip>.
The experimental protocol is described in previous research: <http://www.nature.com/nmeth/journal/v12/n6/abs/nmeth.3393.html>.

#### Experiment summary:

Liquid chromatography: total 15 min run per sample with Waters Acquity UPLC CSH C18 column (100×2.1 mm; 1.7 μm).
Mass spectrometer: SWATH method with negative ion mode.

- MS1 accumulation time, 100 ms
- MS2 accumulation time, 10 ms
- Collision energy, 45 V
- Collision energy spread, 15 V
- Cycle time, 731 ms
- Q1 window, 21 Da
- Mass range, m/z 100-1250
- Modifier, Ammonium formate (HCOONH4)

Additionally, you can watch our tutorial video:
{{< video https://www.youtube.com/watch?v=HV-e9wG9WRo&ab_channel=MS-DIALproject >}}

## 5. LC-MS/MS (Hybrid MS-DDA/SWATH)

## 6. LC-MS/MS (EAD) - deep structural lipid annotation

## 7. DI-IM-MS/MS

## 7. LC-IM-MS/MS
