---
title: "Other utilities of MS-DIAL"
---

## 1. Build MS-DIAL5, 4, and MS-FINDER by yourself!

To build MS-DIAL by yourself, you currently need [Visual Studio](https://visualstudio.microsoft.com).
We plan to make it possible to do this from the command line in the future, but for now, please refer to the video below and do it with Visual Studio.

{{< video https://www.youtube.com/watch?v=5eDAsISjj2I&ab_channel=MS-DIALproject >}}

## 2. MassQL in MS DIAL5

MassQL is a query language designed for mass spectrometry data.
It enables users to search and filter mass spectrometry data using a structured query format, similar to how SQL is used for databases.
MassQL allows for the extraction of specific information from complex datasets, making it easier for researchers and analysts to explore and interpret their mass spectrometry results.
For more details, please refer to [the MassQL Documentation](https://mwang87.github.io/MassQueryLanguage_Documentation/).

The video below demonstrates how to perform peak filtering with MassQL from MS-DIAL5.

{{< video https://www.youtube.com/watch?v=otCq9s1PjAs&ab_channel=MS-DIALproject >}}

## 3. MSCleanR in MS-DIAL5

{{< video https://www.youtube.com/watch?v=c-_mP8A9I04&ab_channel=MS-DIALproject >}}

## 4. Link to MS-FINDER for searching unknowns

MS-FINDER aims to provide solutions for

1. formula predictions
2. fragment annotations
3. structure elucidations

by means of survey scan MS and MS/MS spectra of unknowns.
The detail of MS-FINDER is described in [http://prime.psc.riken.jp/Metabolomics_Software/MS-FINDER/index.html](http://prime.psc.riken.jp/Metabolomics_Software/MS-FINDER/index.html).

:::{.callout-note}
Note that you have to download the MS-FIDNER program from the website above on your PC.
:::

{{< video https://www.youtube.com/watch?v=moHIiTTVfGQ&ab_channel=MS-DIALproject >}}

## 5. Multivariate analysis in MS-DIAL5

{{< video https://www.youtube.com/watch?v=wtOS7F1RgZs&ab_channel=MS-DIALproject >}}

## 5. Bridge to MRMPROBS for DIA-MS or GC/MS data sets

Required software programs and files:

**MRMPROBS**
Download link: http://prime.psc.riken.jp/Metabolomics_Software/MRMPROBS/index.html
For further information: https://systemsomicslab.github.io/mtbinfo.github.io/MRMPROBS/tutorial

Reifycs Analysis Base File Converter (ABF file converter)
Download link: https://www.reifycs.com/abfconverter/

{{< video https://www.youtube.com/watch?v=ndDvHoHDIMk >}}


## 6. Molecular spectrum networking for metabolite annotations

{{< video https://www.youtube.com/watch?v=OxCMpR4umjA&ab_channel=MS-DIALproject >}}

This section introduces how to create molecular spectrum networking in MS-DIAL5.
Molecular spectrum networking is a tool for creating networks that visualize the MS/MS similarities among metabolites.

To follow this video, please download the dataset and check the description in [https://zenodo.org/communities/msdial?q=&l=list&p=1&s=10&sort=newest](https://zenodo.org/communities/msdial?q=&l=list&p=1&s=10&sort=newest).

### The Workflow
1. Download the dataset of "Molecular spectrum networking tutorial dataset" in [https://zenodo.org/communities/msdial?q=&l=list&p=1&s=10&sort=newest](https://zenodo.org/communities/msdial?q=&l=list&p=1&s=10&sort=newest)
2. Open *.mdproject in MS-DIAL5
3. Follow the youtube video 

You can get thses as outputs:
1. The molecular spectrum network that visualize the  MS/MS similarities among metabolites.
2. The dataset to create the network in cytoscape
3. The molecular spectrum network that focusing on one metabolite.
